baseURL = "https://isming.me/"
languageCode = 'zh'
title = 'ç å†œæ˜æ˜æ¡‘'
theme = "zen"
defaultContentLanguage = "zh"
Copyright = '[ç å†œæ˜æ˜æ¡‘çš„åšå®¢](https://isming.me)æ‰€æœ‰å†…å®¹éµå¾ª[ã€ŒCC BY-NC-SA 4.0ã€](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans)åè®®ï¼Œè½¬è½½è¯·ä¿ç•™ç½²åå¹¶æ³¨æ˜æ¥æºã€‚'

[permalinks]
  posts = "/:filename/" # Don't miss the last slash: "/"
  tags = "/tags/:slug/" # Don't miss the last slash: "/"

[params]
 defaultTheme = "light" #light or dark
 contentTypeName="posts"
 MenuMore = "æ›´å¤š"
 dateFormatList = "2006-01-02"
 dateFormatSingle = "2006-01-02"
 dateFormat = "2006-1-2"
 readMore = "é˜…è¯»å…¨æ–‡"
 RssFullText = true
 ShowCodeCopyButtons = true
 ShowPostNavLinks = true
 hasCJKLanguage = true
 reading_speed=120
 readingSpeedRation=1.46
 RssImage='avatar.png'
 rssdescription = 'ç å†œæ˜æ˜æ¡‘ï¼Œä¸€ä¸ªç¨‹åºå‘˜çš„ç”Ÿæ´»å’ŒæŠ€æœ¯å†…å®¹è®°å½•ã€‚'
 Author = "æ˜æ˜åŒå­¦"
 [params.homeInfoParams]
  Title =  "å—¨ï¼Œä½ å¥½ ğŸ‘‹"
  Content = "æ¬¢è¿å…‰ä¸´ç å†œæ˜æ˜æ¡‘çš„å°ç«™ï¼Œè¿™é‡Œæ˜¯æˆ‘çš„ç”Ÿæ´»å’ŒæŠ€æœ¯å†…å®¹è®°å½•ã€‚  <li>ä¸»ä¸šğŸ‘¨â€ğŸ’»ç¨‹åºå‘˜</li><li>å–œæ¬¢ ğŸ“–è¯»é—²ä¹¦ï¼ŒğŸ¬çœ‹ç”µå½±ï¼ŒğŸ“·æ‹ç…§ç‰‡ï¼ŒğŸµå–èŒ¶ã€‚</li><p>æ›´å¤šå…³äºæˆ‘çš„ä¿¡æ¯å¯ä»¥æŸ¥çœ‹ğŸ‘‰[**å…³äºæˆ‘**](https://isming.me/about/)ã€‚</p>"


[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'

[menu]
 [[menu.main]]
  name="é¦–é¡µ"
  url="/"
  weight="1"
 [[menu.main]]
  name="æŠ€æœ¯"
  url="/posts/tech/"
  weight="2"
 [[menu.main]]
  name="è¡Œæ‘„"
  url="/posts/photography/"
  weight="2"
 [[menu.main]]
  name="å½’æ¡£"
  url="/archives/"
  weight="3"
[[menu.main]]
  name="æœç´¢"
  url="/search/"
  weight="4"
 [[menu.main]]
  name="å‹é“¾"
  url="/links/"
  weight="5"
 [[menu.main]]
  name="å…³äº"
  url="/about/"
  weight="6"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'dracula'
    tabWidth = 2


[outputs]
  home = ["HTML","RSS","JSON"]
  page = ["HTML"]


[[params.socialIcons]]
  name = "github"
  url = "https://github.com/sangmingming"

[[params.socialIcons]]
  name = "bilibili"
  url = "https://space.bilibili.com/11883296"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/isming.me/"
[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[[params.socialIcons]]
  name = "email"
  url = "mailto:linming1007@gmail.com"

